import io, json, collections

copy = {
 "uz": {
  "errors": {
    "twoFactorAlreadyOn": "Ikkinchi parol allaqachon yoqilgan.",
    "twoFactorNotOn": "Bu hisobda ikkinchi parol yoqilmagan.",
    "twoFactorInvalid": "Ikkinchi parol notoʻgʻri. Yana {remaining} marta urinib koʻrasiz.",
    "twoFactorLocked": "Koʻp marta notoʻgʻri kiritildi. {minutes} daqiqadan soʻng qayta urinib koʻring yoki ikkinchi parolni tiklang.",
    "twoFactorSameAsPassword": "Ikkinchi parol odatdagi parolingizdan boshqa boʻlishi kerak — aks holda ikkita qulf bitta kalitga ochiladi.",
  },
  "twoFactor": {
    "title": "Ikkinchi parol",
    "subtitle": "Parolingiz toʻgʻri. Endi ikkinchi parolni kiriting — {email} hisobi shu bilan himoyalangan.",
    "password": "Ikkinchi parol",
    "submit": "Davom etish",
    "checking": "Tekshirilmoqda…",
    "forgot": "Ikkinchi parolni unutdingizmi?",
    "notYou": "Bu siz emasmisiz? Chiqish",
    "code": "Pochtangizga kelgan kod",
    "codeSent": "Kod yuborildi. Pochtangizni tekshiring.",
    "newPassword": "Yangi ikkinchi parol",
    "confirmPassword": "Yangi parolni takrorlang",
    "resetSubmit": "Saqlash va kirish",
    "resetting": "Saqlanmoqda…",
    "backToChallenge": "Orqaga qaytish",
  },
  "settings": {
    "title": "Ikkinchi parol",
    "on": "Yoqilgan",
    "off": "Oʻchirilgan",
    "onBody": "Har kirishda odatdagi paroldan soʻng ikkinchi parol ham soʻraladi.",
    "offBody": "Hisobingiz faqat odatdagi parol bilan himoyalangan. Ikkinchi parol qoʻshimcha qulf boʻladi.",
    "turnOn": "Yoqish",
    "sending": "Kod yuborilmoqda…",
    "codeSent": "Pochtangizga kod yubordik. Uni kiriting va ikkinchi parolni tanlang.",
    "code": "Pochtangizga kelgan kod",
    "newPassword": "Ikkinchi parol",
    "confirmPassword": "Takrorlang",
    "differentNote": "Odatdagi parolingizdan boshqa boʻlsin. Uni unutsangiz, pochtangiz orqali tiklaysiz.",
    "confirm": "Yoqish",
    "turningOn": "Yoqilmoqda…",
    "turnOff": "Oʻchirish",
    "turningOff": "Oʻchirilmoqda…",
    "confirmWithPassword": "Tasdiqlash uchun odatdagi parolingizni kiriting",
    "cancel": "Bekor qilish",
  },
 },
 "en": {
  "errors": {
    "twoFactorAlreadyOn": "The second password is already on.",
    "twoFactorNotOn": "This account has no second password.",
    "twoFactorInvalid": "That is not the second password. {remaining} attempts left.",
    "twoFactorLocked": "Too many wrong answers. Try again in {minutes} minutes, or reset the second password.",
    "twoFactorSameAsPassword": "The second password must differ from your usual one — otherwise both locks open with the same key.",
  },
  "twoFactor": {
    "title": "Second password",
    "subtitle": "Your password was right. Now the second one — it is what protects {email}.",
    "password": "Second password",
    "submit": "Continue",
    "checking": "Checking…",
    "forgot": "Forgotten your second password?",
    "notYou": "Not you? Sign out",
    "code": "The code from your inbox",
    "codeSent": "Code sent. Check your inbox.",
    "newPassword": "New second password",
    "confirmPassword": "Repeat the new password",
    "resetSubmit": "Save and continue",
    "resetting": "Saving…",
    "backToChallenge": "Go back",
  },
  "settings": {
    "title": "Second password",
    "on": "On",
    "off": "Off",
    "onBody": "Signing in asks for your second password after the usual one.",
    "offBody": "Your account is protected by your usual password alone. A second password adds another lock.",
    "turnOn": "Turn on",
    "sending": "Sending the code…",
    "codeSent": "We sent a code to your inbox. Enter it, then choose the second password.",
    "code": "The code from your inbox",
    "newPassword": "Second password",
    "confirmPassword": "Repeat it",
    "differentNote": "Make it different from your usual password. If you forget it, your inbox is the way back.",
    "confirm": "Turn on",
    "turningOn": "Turning on…",
    "turnOff": "Turn off",
    "turningOff": "Turning off…",
    "confirmWithPassword": "Type your usual password to confirm",
    "cancel": "Cancel",
  },
 },
 "ru": {
  "errors": {
    "twoFactorAlreadyOn": "Второй пароль уже включён.",
    "twoFactorNotOn": "У этого аккаунта нет второго пароля.",
    "twoFactorInvalid": "Второй пароль неверен. Осталось попыток: {remaining}.",
    "twoFactorLocked": "Слишком много неверных попыток. Повторите через {minutes} минут или сбросьте второй пароль.",
    "twoFactorSameAsPassword": "Второй пароль должен отличаться от обычного — иначе оба замка открываются одним ключом.",
  },
  "twoFactor": {
    "title": "Второй пароль",
    "subtitle": "Пароль верный. Теперь второй — именно он защищает {email}.",
    "password": "Второй пароль",
    "submit": "Продолжить",
    "checking": "Проверяем…",
    "forgot": "Забыли второй пароль?",
    "notYou": "Это не вы? Выйти",
    "code": "Код из почты",
    "codeSent": "Код отправлен. Проверьте почту.",
    "newPassword": "Новый второй пароль",
    "confirmPassword": "Повторите новый пароль",
    "resetSubmit": "Сохранить и войти",
    "resetting": "Сохраняем…",
    "backToChallenge": "Назад",
  },
  "settings": {
    "title": "Второй пароль",
    "on": "Включён",
    "off": "Выключен",
    "onBody": "При входе после обычного пароля спрашивается второй.",
    "offBody": "Аккаунт защищён только обычным паролем. Второй добавит ещё один замок.",
    "turnOn": "Включить",
    "sending": "Отправляем код…",
    "codeSent": "Мы отправили код на почту. Введите его и выберите второй пароль.",
    "code": "Код из почты",
    "newPassword": "Второй пароль",
    "confirmPassword": "Повторите",
    "differentNote": "Пусть он отличается от обычного пароля. Если забудете — почта поможет вернуться.",
    "confirm": "Включить",
    "turningOn": "Включаем…",
    "turnOff": "Выключить",
    "turningOff": "Выключаем…",
    "confirmWithPassword": "Введите обычный пароль для подтверждения",
    "cancel": "Отмена",
  },
 },
}

for loc, groups in copy.items():
    p = f"messages/{loc}.json"
    d = json.load(io.open(p, encoding="utf-8"), object_pairs_hook=collections.OrderedDict)
    d["auth"]["errors"].update(groups["errors"])
    d["auth"]["twoFactor"] = collections.OrderedDict(groups["twoFactor"])
    d["app"]["settings"]["twoFactor"] = collections.OrderedDict(groups["settings"])
    io.open(p, "w", encoding="utf-8", newline="\n").write(
        json.dumps(d, ensure_ascii=False, indent=2) + "\n")

print("2FA copy written in all three languages")
